name: myenv
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch==1.11.0
    - matplotlib==3.5.2
    - numpy>=1.21.6
    - pandas==1.3.5
    - pyvalem==2.5.7
    - scikit-learn==0.24.2
    - joblib==1.0.0